### ISSUE TITLE
Shimmer

### ISSUE THREAD

**Issue by pixnbit** [imtoori/flutter-slide-to-act#3]
Would nice to use Shimmer to have the swipe indication animations. I used to use another library https://github.com/anirudhsharma392/Slider-Button, but it didn't have the customization I need, ended up implementing my own. But it does have a shimmer

**Comment by ijasmv** [comment]
TickerCanceled (This ticker was canceled: _WidgetTicker(created by SlideActionState#0ceec(lifecycle state: created, tickers: tracking 1 ticker)))

i get this error while calling reset

**Comment by imtoori** [comment]
you can implement that using the `child` property and passing a `Text` wrapped in a `Shimmer`
